name: deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 103.23.60.47
          port: 2222
          username: luisgordillo
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd /var/www/html/Proyecto-A4; git pull origin main; npm run build"
